parameters:
    strontium.form.type_extension.specification.class: Strontium\SpecificationBundle\Form\Extension\SpecificationFromTypeExtension
    strontium.form.type.resource_specification.class: Strontium\SpecificationBundle\Form\Type\ResourceSpecificationType

services:
    strontium.form.type_extension.specification:
        class: %strontium.form.type_extension.specification.class%
        arguments:
            - @strontium.specification.factory
        tags:
            - { name: form.type_extension, alias: form }

    strontium.form.type.resource_specification:
         class: %strontium.form.type.resource_specification.class%
         tags:
            - { name: form.type, alias: resource_specification }
