parameters:
    strontium.specification.registry.class: Sylius\Component\Registry\ServiceRegistry
    strontium.specification.factory.class: Strontium\SpecificationBundle\SpecificationFactory

services:
    strontium.specification.registry:
        class: %strontium.specification.registry.class%
        arguments:
            - Strontium\SpecificationBundle\Builder\SpecificationBuilderInterface

    strontium.specification.factory:
        class: %strontium.specification.factory.class%
        arguments:
            - @strontium.specification.registry

    specification.factory:
        alias: strontium.specification.factory
