language: php

sudo: false

php:
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0

before_script:
    - composer install --no-interaction

script: php ./vendor/phpspec/phpspec/bin/phpspec run -f pretty
